#pragma once
#include <lua.h>
enum EActorProp
{
	PROP_ID,
	PROP_DIR,
	PROP_SHOW_BOUNDINGBOX,
	PROP_IS_AUTORUN,
	PROP_IS_DEAD,
	PROP_FRAME_SPEED,
	PROP_ACTOR_TYPE,
	PROP_NAME,
	PROP_AVATAR_ID,
	PROP_WEAPON_AVATAR_ID,
	PROP_SCENE_ID,
	PROP_ROLE_ID,
	PROP_WEAPON_ID,
	PROP_WEAPON_TYPE,
	PROP_ACTION_ID,
	PROP_POS,
	PROP_MOVE_TO_POS,
	PROP_DIR_COUNT,
	PROP_IS_MOVE,
	PROP_MOVE_VELOCITY,
	PROP_IS_COMBAT,
	PROP_TARGET_ID,
	PROP_CAST_ID,
	PROP_IS_CALC_MOVE_LIST,
	PROP_HP,
	PROP_MP,
	PROP_SAY_DURATION,
	PROP_IS_LOCAL,
	PROP_COMBAT_POS,
	PROP_COMBAT_BACKUP_POS,
	PROP_COMBAT_TARGET_POS,
	PROP_TURN_READY
};
enum EActorPropType
{
	PROP_TYPE_BOOL,
	PROP_TYPE_FLOAT,
	PROP_TYPE_INT,
	PROP_TYPE_STR,
	PROP_TYPE_UINT64,
	PROP_TYPE_VEC2
};
void luaopen_actor_enum(lua_State* L);
